remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Snowsmoonjupiter
description: I am at the chapter learning adding a section to my website based on GitHub for Dummies. What really nerves me on that book is that the Win had an update, so not everything fits perfectly as per screenshots. Feel free to add me on GitHub || check my LinkedIn.
github_username: snowsmoonjupiter
